version: 2
jobs:
  build:
    docker: 
      - image: node:8.0
    steps:
      - run:
          name: "Checking Node Version"
          command: node --version
      - run:
          name: "Checking npm version"
          command: npm --version
      - run:
          name: "Install npm dependencies"
          command: npm install 
